version: "3"
services:
    app:
        container_name: user
        restart: always
        build: .
        ports:
            - "8080:7575"
        links:
            - "mongo"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"
